name: Build and Deploy GH Pages
on: [push]
jobs:
  pages:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Build Podman container
        run: podman build -t plurimath-builder .
      - name: Run Podman container to build demo
        run: podman run --rm -it -v.:/srv:z plurimath-builder bash -c 'cd /srv; ./setup.sh; ./build.sh; mkdir gh-pages; cd gh-pages; cp ../demo.html ../index.mjs ../plurimath-opal.mjs ../plurimath-opal.min.mjs .'
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: gh-pages # The folder the action should deploy.
